sudo: false
language: ruby
rvm:
  - 2.1.7
install:
  - travis_retry bundle install
  - travis_retry npm install -g grunt-cli
before_script:
  - rvm install 2.1.7
  - rvm use 2.1.7 --fuzzy
  - npm install
script:
  - grunt build
after_success:
  - bash deploy/script.bash
  - openssl aes-256-cbc -K $encrypted_64ebfcd72846_key -iv $encrypted_64ebfcd72846_iv -in deploy/notification.bash.enc -out deploy/notification.bash -d
  - bash deploy/notification.bash
notifications:
  slack:
    - secure: 'lgIokb+6DIhsWC1cMWflbuDSRhVKHRYY3B4q2IgFKestlnwYnvbJsnQuU0wEKHFscjxD6fIZpMooxKPhqz3M8GFA6qIBizsD4p0H7kjSg+gvHWmxkn11IVdjxEyqJZOjeSDNK+5l/Jg8eBr0nZm6umlciO0apkZcE23javc1uBM='
